const express = require('express')
const router = express.Router()
const userController = require('../controllers/user')
const { protect } = require('../middlewares/auth')
const upload = require('../middlewares/upload')

router.get('/', userController.getData)
router.get('/:id', userController.getProfile)
router.get('/findemail/:email', userController.findEmail)
router.post('/login', userController.login)
router.post('/register', userController.insertData)
router.put('/checkemail/:email', userController.checkEmail)
router.put('/changepassword/:email', userController.changePassword)
router.put('/verify/:email', userController.verify)
router.put('/setaddress/:id', userController.updateAddress)
router.put('/photo/:id', upload.single('photo'), userController.updatePhoto)
router.put('/:id', protect, upload.single('photo'), userController.updateData)
router.delete('/:id', protect, userController.deleteData)

module.exports = router